.TH "ProiectIP.Intrebare" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.Intrebare \- Clasa \fBIntrebare\fP este folosita pentru a ne permite sa cream un obiect de tip \fBIntrebare\fP, fiecare obiect avand un enunt, 4 variante si un int care va spune care varianta este cea corecta\&. /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntrebare\fP (string enunt, string var1, string var2, string var3, string var4, int varCorecta)"
.br
.RI "Constructorul clasei\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBnr\fP = 0"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBEnunt\fP\fC [get]\fP"
.br
.RI "Returneaza enuntul intrebarii\&. "
.ti -1c
.RI "string \fBVarianta1\fP\fC [get]\fP"
.br
.RI "Returneaza prima varianta\&. "
.ti -1c
.RI "string \fBVarianta2\fP\fC [get]\fP"
.br
.RI "Returneaza a doua varianta\&. "
.ti -1c
.RI "string \fBVarianta3\fP\fC [get]\fP"
.br
.RI "Returneaza a treia varianta\&. "
.ti -1c
.RI "string \fBVarianta4\fP\fC [get]\fP"
.br
.RI "Returneaza a patra varianta\&. "
.ti -1c
.RI "int \fBVariantaCorecta\fP\fC [get]\fP"
.br
.RI "Returneaza care este varianta corecta\&. "
.ti -1c
.RI "bool \fBVerificaFlag\fP\fC [get]\fP"
.br
.RI "Verifica daca valoarea introdusa ca raspuns corect este valida\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa \fBIntrebare\fP este folosita pentru a ne permite sa cream un obiect de tip \fBIntrebare\fP, fiecare obiect avand un enunt, 4 variante si un int care va spune care varianta este cea corecta\&. /summary> 
.PP
Definition at line \fB31\fP of file \fBIntrebare\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.Intrebare\&.Intrebare (string enunt, string var1, string var2, string var3, string var4, int varCorecta)"

.PP
Constructorul clasei\&. 
.PP
Definition at line \fB42\fP of file \fBIntrebare\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ProiectIP\&.Intrebare\&.nr = 0\fC [static]\fP"

.PP
Definition at line \fB39\fP of file \fBIntrebare\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string ProiectIP\&.Intrebare\&.Enunt\fC [get]\fP"

.PP
Returneaza enuntul intrebarii\&. 
.PP
Definition at line \fB58\fP of file \fBIntrebare\&.cs\fP\&.
.SS "string ProiectIP\&.Intrebare\&.Varianta1\fC [get]\fP"

.PP
Returneaza prima varianta\&. 
.PP
Definition at line \fB66\fP of file \fBIntrebare\&.cs\fP\&.
.SS "string ProiectIP\&.Intrebare\&.Varianta2\fC [get]\fP"

.PP
Returneaza a doua varianta\&. 
.PP
Definition at line \fB74\fP of file \fBIntrebare\&.cs\fP\&.
.SS "string ProiectIP\&.Intrebare\&.Varianta3\fC [get]\fP"

.PP
Returneaza a treia varianta\&. 
.PP
Definition at line \fB82\fP of file \fBIntrebare\&.cs\fP\&.
.SS "string ProiectIP\&.Intrebare\&.Varianta4\fC [get]\fP"

.PP
Returneaza a patra varianta\&. 
.PP
Definition at line \fB90\fP of file \fBIntrebare\&.cs\fP\&.
.SS "int ProiectIP\&.Intrebare\&.VariantaCorecta\fC [get]\fP"

.PP
Returneaza care este varianta corecta\&. 
.PP
Definition at line \fB98\fP of file \fBIntrebare\&.cs\fP\&.
.SS "bool ProiectIP\&.Intrebare\&.VerificaFlag\fC [get]\fP"

.PP
Verifica daca valoarea introdusa ca raspuns corect este valida\&. 
.PP
Definition at line \fB108\fP of file \fBIntrebare\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
