.TH "ProiectIP.ChestionarLimbaSiLiteraturaRomana" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.ChestionarLimbaSiLiteraturaRomana \- Aceasta este clasa care poate fi folista pentru a instantia un obiect de tip chestionar cu intrebari din domeniul Limba si Literatura romana\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IChestionar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChestionarLimbaSiLiteraturaRomana\fP ()"
.br
.ti -1c
.RI "string \fBGetEnunt\fP (int x)"
.br
.ti -1c
.RI "string \fBGetVar1\fP (int x)"
.br
.ti -1c
.RI "string \fBGetVar2\fP (int x)"
.br
.ti -1c
.RI "string \fBGetVar3\fP (int x)"
.br
.ti -1c
.RI "string \fBGetVar4\fP (int x)"
.br
.ti -1c
.RI "int \fBGetRaspuns\fP (int x)"
.br
.ti -1c
.RI "string \fBPicture\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Aceasta este clasa care poate fi folista pentru a instantia un obiect de tip chestionar cu intrebari din domeniul Limba si Literatura romana\&. /summary> 
.PP
Definition at line \fB32\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.ChestionarLimbaSiLiteraturaRomana ()"

.PP
Definition at line \fB35\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetEnunt (int x)"

.PP
Definition at line \fB61\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "int ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetRaspuns (int x)"

.PP
Definition at line \fB91\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetVar1 (int x)"

.PP
Definition at line \fB67\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetVar2 (int x)"

.PP
Definition at line \fB73\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetVar3 (int x)"

.PP
Definition at line \fB79\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.GetVar4 (int x)"

.PP
Definition at line \fB85\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.
.SS "string ProiectIP\&.ChestionarLimbaSiLiteraturaRomana\&.Picture ()"

.PP
Definition at line \fB97\fP of file \fBChestionarLimbaSiLiteraturaRomana\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
