.TH "ProiectIP.TextBoxException" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.TextBoxException \- Clasa ce reprezinta o exceptie de tip textbox\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextBoxException\fP (String message)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override String \fBMessage\fP\fC [get]\fP"
.br
.RI "Returneaza mesajul exceptiei\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa ce reprezinta o exceptie de tip textbox\&. /summary> 
.PP
Definition at line \fB30\fP of file \fBTextBoxException\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.TextBoxException\&.TextBoxException (String message)"

.PP
Definition at line \fB33\fP of file \fBTextBoxException\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override String ProiectIP\&.TextBoxException\&.Message\fC [get]\fP"

.PP
Returneaza mesajul exceptiei\&. 
.PP
Definition at line \fB40\fP of file \fBTextBoxException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
