.TH "ProiectIP.Calculeaza" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.Calculeaza \- Clasa \fBCalculeaza\fP se va folosi pentru a calcula scorul in functie de numarul intrebarilor corecte si totale\&. Ea este apelata in clasele ScorPartial si ScorFinal\&. /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculeaza\fP (decimal x, decimal y)"
.br
.RI "Constructorul clasei care primeste cei 2 operanzi si face verificarea sa vada daca acestia sunt valizi\&. "
.ti -1c
.RI "void \fBCalcul\fP ()"
.br
.RI "Calculul scorului final care va fi folosit pentru a imparti numarul de raspunsuri corecte la numarul de intrebari pentru a obtine procentajul\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBValid\fP\fC [get]\fP"
.br
.RI "Returneaza daca argumentele date functiei sunt valide\&. "
.ti -1c
.RI "decimal \fBRezultat\fP\fC [get]\fP"
.br
.RI "Returneaza rezultatul calculului\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa \fBCalculeaza\fP se va folosi pentru a calcula scorul in functie de numarul intrebarilor corecte si totale\&. Ea este apelata in clasele ScorPartial si ScorFinal\&. /summary> 
.PP
Definition at line \fB31\fP of file \fBCalculeaza\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.Calculeaza\&.Calculeaza (decimal x, decimal y)"

.PP
Constructorul clasei care primeste cei 2 operanzi si face verificarea sa vada daca acestia sunt valizi\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBCalculeaza\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ProiectIP\&.Calculeaza\&.Calcul ()"

.PP
Calculul scorului final care va fi folosit pentru a imparti numarul de raspunsuri corecte la numarul de intrebari pentru a obtine procentajul\&. 
.PP
Definition at line \fB56\fP of file \fBCalculeaza\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "decimal ProiectIP\&.Calculeaza\&.Rezultat\fC [get]\fP"

.PP
Returneaza rezultatul calculului\&. 
.PP
Definition at line \fB73\fP of file \fBCalculeaza\&.cs\fP\&.
.SS "bool ProiectIP\&.Calculeaza\&.Valid\fC [get]\fP"

.PP
Returneaza daca argumentele date functiei sunt valide\&. 
.PP
Definition at line \fB63\fP of file \fBCalculeaza\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
