.TH "Test.UnitTest1" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test.UnitTest1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestScor_0\fP ()"
.br
.ti -1c
.RI "void \fBTestScor_minus5\fP ()"
.br
.ti -1c
.RI "void \fBTestScor_minusminus\fP ()"
.br
.ti -1c
.RI "void \fBTestScor_zero\fP ()"
.br
.ti -1c
.RI "void \fBTestScor_calcul\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_varsta\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_minus\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_maiMicCa16\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_anViitor\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_1922\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_1921\fP ()"
.br
.ti -1c
.RI "void \fBTestCalculVarsta_zero\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_litere\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_litereCorect\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_semn\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_spatiu\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_literaMare\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_AreLitereDiferite_1\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_AreLitereDiferite_2\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_AreLitereDiferite_3\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_AreLitereDiferite_4\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_AreLitereDiferite_5\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_literaMica\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaNume_gol\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaIntrebare\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaVariantaCorecta\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaFlagIntrebare\fP ()"
.br
.ti -1c
.RI "void \fBTestVerificaFlagIntrebareValoareMare\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBUnitTest1\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_1921 ()"

.PP
Definition at line \fB96\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_1922 ()"

.PP
Definition at line \fB89\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_anViitor ()"

.PP
Definition at line \fB83\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_maiMicCa16 ()"

.PP
Definition at line \fB77\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_minus ()"

.PP
Definition at line \fB71\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_varsta ()"

.PP
Definition at line \fB64\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestCalculVarsta_zero ()"

.PP
Definition at line \fB102\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestScor_0 ()"

.PP
Definition at line \fB28\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestScor_calcul ()"

.PP
Definition at line \fB56\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestScor_minus5 ()"

.PP
Definition at line \fB36\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestScor_minusminus ()"

.PP
Definition at line \fB43\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestScor_zero ()"

.PP
Definition at line \fB50\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaFlagIntrebare ()"

.PP
Definition at line \fB183\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaFlagIntrebareValoareMare ()"

.PP
Definition at line \fB189\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaIntrebare ()"

.PP
Definition at line \fB171\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_AreLitereDiferite_1 ()"

.PP
Definition at line \fB135\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_AreLitereDiferite_2 ()"

.PP
Definition at line \fB141\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_AreLitereDiferite_3 ()"

.PP
Definition at line \fB146\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_AreLitereDiferite_4 ()"

.PP
Definition at line \fB151\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_AreLitereDiferite_5 ()"

.PP
Definition at line \fB156\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_gol ()"

.PP
Definition at line \fB166\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_literaMare ()"

.PP
Definition at line \fB130\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_literaMica ()"

.PP
Definition at line \fB161\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_litere ()"

.PP
Definition at line \fB109\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_litereCorect ()"

.PP
Definition at line \fB115\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_semn ()"

.PP
Definition at line \fB120\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaNume_spatiu ()"

.PP
Definition at line \fB125\fP of file \fBUnitTest1\&.cs\fP\&.
.SS "void Test\&.UnitTest1\&.TestVerificaVariantaCorecta ()"

.PP
Definition at line \fB177\fP of file \fBUnitTest1\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
