.TH "Form1.Designer.cs" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Form1.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProiectIP\&.Form1\fP"
.br
.RI "Clasa ce va lansa in executie interfata pentru meniul chestionarului care permite utilizatorului sa aleaga ce modul sa parcurga\&. /summary> "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProiectIP\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
