.TH "ProiectIP.Form1" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.Form1 \- Clasa ce va lansa in executie interfata pentru meniul chestionarului care permite utilizatorului sa aleaga ce modul sa parcurga\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm1\fP ()"
.br
.RI "constructorul public al clasei "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBdomeniu\fP"
.br
.ti -1c
.RI "static string \fBnume\fP"
.br
.ti -1c
.RI "static int \fBvarsta\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa ce va lansa in executie interfata pentru meniul chestionarului care permite utilizatorului sa aleaga ce modul sa parcurga\&. /summary> 
.PP
Definition at line \fB16\fP of file \fBForm1\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.Form1\&.Form1 ()"

.PP
constructorul public al clasei 
.PP
Definition at line \fB24\fP of file \fBForm1\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ProiectIP\&.Form1\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBForm1\&.Designer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ProiectIP\&.Form1\&.domeniu\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBForm1\&.cs\fP\&.
.SS "string ProiectIP\&.Form1\&.nume\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBForm1\&.cs\fP\&.
.SS "int ProiectIP\&.Form1\&.varsta\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBForm1\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
