.TH "ProiectIP.Form3" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.Form3 \- Clasa ce da functionalitatea lui \fBForm3\fP, \fBForm3\fP fiind interfata afisata atunci cand un modul este completat, sau cand tot testul este terminat\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm3\fP (int scor, bool flag)"
.br
.RI "constructorul public "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa ce da functionalitatea lui \fBForm3\fP, \fBForm3\fP fiind interfata afisata atunci cand un modul este completat, sau cand tot testul este terminat\&. /summary> 
.PP
Definition at line \fB17\fP of file \fBForm3\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.Form3\&.Form3 (int scor, bool flag)"

.PP
constructorul public 
.PP
Definition at line \fB21\fP of file \fBForm3\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ProiectIP\&.Form3\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBForm3\&.Designer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
