.TH "ProiectIP" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForm1\fP"
.br
.RI "Clasa ce va lansa in executie interfata pentru meniul chestionarului care permite utilizatorului sa aleaga ce modul sa parcurga\&. /summary> "
.ti -1c
.RI "class \fBForm2\fP"
.br
.RI "Aceasta clasa da functionalitatea lui \fBForm2\fP, care reprezinta interfata afisata atunci cand un chestionar este in curs, care afiseaza intrebarile si variantele\&. /summary> "
.ti -1c
.RI "class \fBForm3\fP"
.br
.RI "Clasa ce da functionalitatea lui \fBForm3\fP, \fBForm3\fP fiind interfata afisata atunci cand un modul este completat, sau cand tot testul este terminat\&. /summary> "
.ti -1c
.RI "class \fBInvalidNameException\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
