.TH "ProiectIP.Form2" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.Form2 \- Aceasta clasa da functionalitatea lui \fBForm2\fP, care reprezinta interfata afisata atunci cand un chestionar este in curs, care afiseaza intrebarile si variantele\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm2\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Aceasta clasa da functionalitatea lui \fBForm2\fP, care reprezinta interfata afisata atunci cand un chestionar este in curs, care afiseaza intrebarile si variantele\&. /summary> 
.PP
Definition at line \fB17\fP of file \fBForm2\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.Form2\&.Form2 ()"

.PP
Definition at line \fB26\fP of file \fBForm2\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ProiectIP\&.Form2\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBForm2\&.Designer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
