.TH "ProiectIP" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScorFinal\fP"
.br
.RI "Aceasta clasa este folosita pentru a calcula scorul final, fiind un singleton deoarece avem nevoie de o singura instanta a ei, scorul final fiind doar unul\&. /summary> "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
