.TH "ProiectIP.VerificaNume" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.VerificaNume \- Clasa care va verifica corectitudinea numelui introdus la logare\&. /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBAreDoarLitere\fP (string s)"
.br
.RI "Functia care vrifica daca string-ul introdus are doar litere\&. "
.ti -1c
.RI "static bool \fBIncepeCuLiteraMare\fP (string s)"
.br
.RI "Functia care verifica daca string-ul incepe cu litera mare\&. "
.ti -1c
.RI "static bool \fBContineLitereDiferite\fP (string s)"
.br
.RI "Functie ce primeste ca parametru un string si va verifica daca contine litere diferite sau aceeasi litera ex: Aaaa va returna false\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa care va verifica corectitudinea numelui introdus la logare\&. /summary> 
.PP
Definition at line \fB29\fP of file \fBVerificaNume\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool ProiectIP\&.VerificaNume\&.AreDoarLitere (string s)\fC [static]\fP"

.PP
Functia care vrifica daca string-ul introdus are doar litere\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
returneaza true daca incepe cu litera mare si false daca cu mica
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBVerificaNume\&.cs\fP\&.
.SS "static bool ProiectIP\&.VerificaNume\&.ContineLitereDiferite (string s)\fC [static]\fP"

.PP
Functie ce primeste ca parametru un string si va verifica daca contine litere diferite sau aceeasi litera ex: Aaaa va returna false\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBVerificaNume\&.cs\fP\&.
.SS "static bool ProiectIP\&.VerificaNume\&.IncepeCuLiteraMare (string s)\fC [static]\fP"

.PP
Functia care verifica daca string-ul incepe cu litera mare\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
returneaza true daca incepe cu litera mare si false daca cu mica
.RE
.PP

.PP
Definition at line \fB46\fP of file \fBVerificaNume\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
