.TH "CalculeazaVarsta.cs" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CalculeazaVarsta.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProiectIP\&.CalculeazaVarsta\fP"
.br
.RI "Clasa \fBCalculeazaVarsta\fP se va folosi pentru a calcula varsta in functie de anul nasterii introdus de utilizator si de anul curent\&. Este nevoie de aceasta clasa pentru a sti daca persoana care se logheaza are intre 16 si 100 de ani sau daca a introdus o data valida\&. /summary> "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProiectIP\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
