.TH "ProiectIP.CalculeazaVarsta" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.CalculeazaVarsta \- Clasa \fBCalculeazaVarsta\fP se va folosi pentru a calcula varsta in functie de anul nasterii introdus de utilizator si de anul curent\&. Este nevoie de aceasta clasa pentru a sti daca persoana care se logheaza are intre 16 si 100 de ani sau daca a introdus o data valida\&. /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculeazaVarsta\fP (int y)"
.br
.RI "Constructorul care primeste ca parametru un an si va verifica daca acesta este unul valid\&. "
.ti -1c
.RI "void \fBCalcul\fP ()"
.br
.RI "Calculeaza varsta in functie de an si verifica daca este o varsta acceptata in aplicatia noastra\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBValid\fP\fC [get]\fP"
.br
.RI "Returneaza daca argumentele date functiei sunt valide\&. "
.ti -1c
.RI "int \fBRezultat\fP\fC [get]\fP"
.br
.RI "Returneaza rezultatul calculului\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clasa \fBCalculeazaVarsta\fP se va folosi pentru a calcula varsta in functie de anul nasterii introdus de utilizator si de anul curent\&. Este nevoie de aceasta clasa pentru a sti daca persoana care se logheaza are intre 16 si 100 de ani sau daca a introdus o data valida\&. /summary> 
.PP
Definition at line \fB30\fP of file \fBCalculeazaVarsta\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.CalculeazaVarsta\&.CalculeazaVarsta (int y)"

.PP
Constructorul care primeste ca parametru un an si va verifica daca acesta este unul valid\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBCalculeazaVarsta\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ProiectIP\&.CalculeazaVarsta\&.Calcul ()"

.PP
Calculeaza varsta in functie de an si verifica daca este o varsta acceptata in aplicatia noastra\&. 
.PP
Definition at line \fB54\fP of file \fBCalculeazaVarsta\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int ProiectIP\&.CalculeazaVarsta\&.Rezultat\fC [get]\fP"

.PP
Returneaza rezultatul calculului\&. 
.PP
Definition at line \fB74\fP of file \fBCalculeazaVarsta\&.cs\fP\&.
.SS "bool ProiectIP\&.CalculeazaVarsta\&.Valid\fC [get]\fP"

.PP
Returneaza daca argumentele date functiei sunt valide\&. 
.PP
Definition at line \fB64\fP of file \fBCalculeazaVarsta\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
