.TH "ProiectIP.ChestionarFactory" 3 "Wed May 25 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProiectIP.ChestionarFactory \- Clasa de tip Factory ce va decide ce fel de obiect va fi creat in functie de tipul dat\&. /summary>  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChestionarFactory\fP (int tip)"
.br
.ti -1c
.RI "IChestionar \fBGetChestionar\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Clasa de tip Factory ce va decide ce fel de obiect va fi creat in functie de tipul dat\&. /summary> 
.PP
Definition at line \fB30\fP of file \fBChestionarFactory\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProiectIP\&.ChestionarFactory\&.ChestionarFactory (int tip)"

.PP
Definition at line \fB34\fP of file \fBChestionarFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "IChestionar ProiectIP\&.ChestionarFactory\&.GetChestionar ()"

.PP
Definition at line \fB68\fP of file \fBChestionarFactory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
